In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices2.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [2]:
import math
median_bedroom = math.floor(df.bedrooms.median())
median_bedroom

NameError: name 'df' is not defined

In [4]:
df.bedrooms.fillna(median_bedroom,inplace=True)

In [5]:
reg = linear_model.LinearRegression()

In [6]:
reg.fit(df[['area','bedrooms','age']],df.price) ## area, bedroom,age are indepentent variable nd target area is price

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

In [9]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [10]:
reg.predict([[2600,3,20]])

array([518217.63297611])

In [11]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

In [3]:
!pip install word2number
from word2number import w2n

In [4]:
df_new =pd.read_csv('hiring.csv')
df_new

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df_new.experience.fillna("zero",inplace=True)

In [6]:
test_score =math.floor(df_new['test_score(out of 10)'].mean())
df_new['test_score(out of 10)'] = df_new['test_score(out of 10)'].fillna(test_score)

In [7]:
df_new.experience = df_new.experience.apply(w2n.word_to_num)

In [8]:
df_new

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [18]:
x=df_new[['experience','test_score(out of 10)','interview_score(out of 10)']]

In [19]:
y=df_new[['salary($)']]

In [9]:
import statsmodels.formula.api as smapi

In [23]:
lm = smapi.ols(formula="y~x",data=df_new).fit()

In [24]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.977
Model:                            OLS   Adj. R-squared:                  0.960
Method:                 Least Squares   F-statistic:                     56.67
Date:                Tue, 23 Jun 2020   Prob (F-statistic):           0.000983
Time:                        20:17:58   Log-Likelihood:                -70.528
No. Observations:                   8   AIC:                             149.1
Df Residuals:                       4   BIC:                             149.4
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1.499e+04   7386.210      2.030      0.112   -5514.756    3.55e+04
x[0]        2922.2690    225.137     12.980      0.000    2297.189    3547.349
x[1]        2221.3091    730.149      3.042      0.038     194.091    4248.527
x[2]        2147.4826    557.362      3.853      0.018     599.998    3694.967
==============================================================================
Omnibus:                        0.916   Durbin-Watson:                   1.788
Prob(Omnibus):                  0.632   Jarque-Bera (JB):                0.693
Skew:                          -0.468   Prob(JB):                        0.707
Kurtosis:                       1.903   Cond. No.                         111.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
reg = linear_model.LinearRegression()

In [19]:
reg.fit(df_new[['experience','test_score(out of 10)','interview_score(out of 10)']],df_new['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
reg.predict([[12,10,10]])

array([93747.79628651])

In [21]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [22]:
reg.intercept_

14992.65144669314